base_url = "https://dincertekin.com"
title = "dincertekin"
description = "Posts about cybersecurity and software engineering."
theme = "apollo"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true

fediverse = false         # author attribution
fediverse_creator = ""    # e.g. @user@instance

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/videos", url = "/videos", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "youtube", url = "https://youtube.com/@dincertekin/", icon = "youtube" },
    { name = "github", url = "https://github.com/dincertekin/", icon = "github" },
    { name = "instagram", url = "https://instagram.com/dincertekin0", icon = "instagram" },
    { name = "linkedin", url = "https://linkedin.com/in/dincertekin/", icon = "linkedin" },
]

stylesheets = [
    # "custom.css"             # at /static/custom.css
]

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = true

[extra.analytics.google]
tracking_id = "G-PBWHZ944R9"  # Your Google Analytics tracking ID
